pool: windows-latest

trigger: 
  - develop
  - main

stages: 
  - stage: build
    displayName: "Compilando a minha aplicação"
    jobs:
      - job: backend
        displayName: "Compilando a API do sistema"
        steps: 
          - task: NuGetCommand@2
            displayName: "Restaurando pacotes NuGet"
            inputs:
              command: 'restore'
              restoreSolution: '**/*.sln'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            displayName: "Compilando o projeto"
            inputs:
              command: 'build'
              projects: '**/*.csproj'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactsDirectory)'
              ArtifactName: 'backendCompilado'
              publishLocation: 'Container'
  
  - stage: release
    displayName: "Lançamento do produto no ambiente dev"
    dependsOn: build
    jobs:
      - job: backendRelease
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'backendCompilado'
            downloadPath: '$(System.ArtifactsDirectory)'


