pool: windows-latest

trigger: 
  - develop
  - main

variables:
  buildConfiguration: "Release"
  senhaBD: $(SENHADB)
  ${{ if eq( variables['Build.SourceBranchName'], 'develop' ) }}:
    baseUrl: "https://ambienteBeta.azurewebsites.net/"
  ${{ if eq( variables['Build.SourceBranchName'], 'main' ) }}:
    baseUrl: "https://ambienteProd.azurewebsites.net/"

stages: 
  - stage: build
    displayName: "Compilando a minha aplicação"
    jobs:
      - job: backend
        displayName: "Compilando a API do sistema"
        steps: 
          - task: NuGetCommand@2
            displayName: "Restaurando pacotes NuGet"
            inputs:
              command: 'restore'
              restoreSolution: '**/*.sln'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            displayName: "Compilando o projeto"
            inputs:
              command: 'build'
              projects: '**/*.csproj'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactsDirectory)'
              ArtifactName: 'backendCompilado'
              publishLocation: 'Container'
  
  - stage: release
    displayName: "Lançamento do produto no ambiente dev"
    dependsOn: build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    jobs:
      - job: backendRelease
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'backendCompilado'
            downloadPath: '$(System.ArtifactsDirectory)'

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Visual Studio Enterprise(66617915-b071-43f5-b408-ccfcf9c4ab1e)'
            appType: 'webApp'
            WebAppName: 'vtnservices'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

  - stage: release
    displayName: "Lançamento do produto no ambiente de produção"
    dependsOn: build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: backendRelease
        steps:
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'backendCompilado'
            downloadPath: '$(System.ArtifactsDirectory)'

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Visual Studio Enterprise(66617915-b071-43f5-b408-ccfcf9c4ab1e)'
            appType: 'webApp'
            WebAppName: 'vtnservices'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
